name: Validate Dev Container

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Dev Container
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: mujoco-dev-container:latest
        build-args: |
          BUILD_PLATFORM=linux/amd64
          USERNAME=vscode
          USER_UID=1000
          USER_GID=1000

    - name: Test Container
      run: |
        docker run --rm mujoco-dev-container:latest python3 -c "import mujoco; print('MuJoCo import successful')"

    # Optional: Install and use Dev Container CLI
    - name: Install Dev Container CLI
      run: npm install -g @devcontainers/cli

    - name: Validate Dev Container configuration
      run: devcontainer build --workspace-folder .
