name: Validate Dev Container

permissions:
  checks: write
  contents: read
  statuses: write

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch || github.head_ref }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Dev Container
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: mujoco-dev-container:latest
        build-args: |
          BUILD_PLATFORM=linux/amd64
          USERNAME=vscode
          USER_UID=1000
          USER_GID=1000

    - name: Test Container
      run: |
        docker run --rm mujoco-dev-container:latest python3 -c "import mujoco; print('MuJoCo import successful')"

    - name: Install Dev Container CLI (optional)
      run: npm install -g @devcontainers/cli

    - name: Validate Dev Container configuration
      run: devcontainer build --workspace-folder .

    - name: Report success
      if: success()
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'success',
            context: 'build',
            description: 'The build succeeded!',
          })

    - name: Report failure
      if: failure()
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'failure',
            context: 'build',
            description: 'The build failed!',
          })
